[package]
name = "astratrade_contracts"
version = "0.1.0"

[dependencies]
starknet = ">=2.8.0"

[cairo]
sierra-replace-ids = true

[tool.cairo]
casm = true

[[target.starknet-contract]]

[[bin]]
name = "vault"
path = "src/contracts/vault.cairo"

[[bin]]
name = "paymaster" 
path = "src/contracts/paymaster.cairo"

[[bin]]
name = "exchange"
path = "src/contracts/exchange.cairo"

[[bin]]
name = "exchange_v2"
path = "src/contracts/exchange_v2.cairo" 